### ISSUE TITLE
Next/Prev Loop

### ISSUE THREAD

**Issue by vseager** [magefan/module-blog#284] opened 2019-10-22 16:51 UTC
When two posts end up with the exact same publish time, the next/prev buttons end up in an infinite loop:

The issue lies in the `getNextPost` and `getPrevPost` functions:

https://github.com/magefan/module-blog/blob/master/Block/Post/View/NextPrev.php#L110-L113

```
            $collection = $this->_getFrontendCollection()->addFieldToFilter(
                'publish_time',
                [
                    'lteq' => $this->getPost()->getPublishTime()
                ]
            )
```

I guess it would need to be something like this (not untested):

```
            $collection = $this->_getFrontendCollection()
                 ->addFieldToFilter('publish_time', 'lteq' => $this->getPost()->getPublishTime())
                 ->addFieldToFilter('id', 'neq' => $this->getPost()->getId());
```

**Comment by magefan** [comment] 2019-10-25 06:39
@vseager , the issue is fixed https://github.com/magefan/module-blog/commit/7eb6b5e07228dc9ebeb18a97e95e9c3e50c77f3b. This fix will be included in the next [Magento 2 Blog](https://magefan.com/magento2-blog-extension) release.

**Closed** 2019-10-26 18:06 UTC
